public enum ItemType
{
    Note,
    Key,
    RatTrap,
    Marker,
    Screwdriver,
    GasCanister,
    Wrench,
    DefectivePrinterPaper,
    ResignationPaper,
    ElevatorHint,

}

public enum GameState
{
    Default,
    EnteredOffice,
    KenGreeted,
    ComputerIntroDone,
    DocGiven1,
    DocGiven2,
    DocGiven3,
    PhoneRead,
    IntroSequenceDone,
    ReadNote,
    EnteredBathroom,
    SinkBroken,
    SinkRepaired,
    ReturnedToDesk,
    RatTrapPlaced,
    NumberDialed,
    PipePuzzleComplete1,
    PipePuzzleComplete2,
    PipePuzzleComplete3,
    AllPipePuzzlesCompleted,
    PrinterFueled,
    InsideJanitorOffice,
    ResignationPapersPrinted,
    JanitorDoorUnlocked,
    ReachedUpperElevator,
    JanitorSpokenTo,
    ElevatorPuzzleDone,
    ElevatorButtonSequencePressed,
    EnteredReception,
    MinesweeperDone,
    ShuttersOpened
}